### ISSUE TITLE
Port collision when both gateway and reva loads gateway.toml

### ISSUE THREAD

**Issue by mirekys** [cs3org/charts#3]
There is a collision of used ports as both reva and gateway containers use
the same [gateway.toml](https://github.com/cs3org/charts/pull/2/commits/a78d99e5d9b1a156991cdae31f498571a581da28#diff-fe8f2f4d95cd919ba8faf761f9e7b19eR55)

Related: #2

**Comment by SamuAlfageme** [comment]
This is due to the `-dev-dir` (https://github.com/cs3org/reva/pull/416) picking all the files mounted from the `ConfigMap` and the pod's network space being shared. I'll fix it by creating a second `ConfigMap` for the gateway and its cfg. files.

In a production-ready future, we shall not run multiple revad goroutines in just one container but rather have one container per config file (+ its additional json files).

**Comment by SamuAlfageme** [comment]
Won't reproduce again as we changed the pod layout after https://github.com/cs3org/reva/pull/826 and removed the `workDir` and `args` parameters from the chart values to prevent using `-dev-dir` inside the pod in https://github.com/cs3org/charts/pull/7.

Thanks for reporting @mirekys!
